#Faça um programa que leia algo do teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele
algo = input('Digite algo: ')
print('O tipo primitivo desse valor é ', (type(algo)))
print('Só tem espaço? ', algo.isspace())
print('É um número? ', algo.isnumeric())
print('É alfabetico? ', algo.isalpha())
print('É alfanumerico? ', algo.isalnum())
print('Está em maiúsculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalizada? ', algo.istitle())
